In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('dataset/stud.csv')
df.head(10)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.67
1,female,group C,some college,standard,completed,69,90,88,247,82.33
2,female,group B,master's degree,standard,none,90,95,93,278,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.33
4,male,group C,some college,standard,none,76,78,75,229,76.33
5,female,group B,associate's degree,standard,none,71,83,78,232,77.33
6,female,group B,some college,standard,completed,88,95,92,275,91.67
7,male,group B,some college,free/reduced,none,40,43,39,122,40.67
8,male,group D,high school,free/reduced,completed,64,64,67,195,65.00
9,female,group B,high school,free/reduced,none,38,60,50,148,49.33

In [3]:
df.isna().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
total_score                    0
average_score                  0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
 8   total_score                  1000 non-null   int64
 9   average_score                1000 non-null   float64
dtypes: float64(1), int64(4), object(5)
memory usage: 78.2+ KB

In [5]:
for i in df.columns:
    print(f'\nColumn : {i}')
    print(f'{i} : {df[i].unique()}')

Column : gender
gender : ['female' 'male']

Column : race_ethnicity
race_ethnicity : ['group B' 'group C' 'group A' 'group D' 'group E']

Column : parental_level_of_education
parental_level_of_education : ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

Column : lunch
lunch : ['standard' 'free/reduced']

Column : test_preparation_course
test_preparation_course : ['none' 'completed']

Column : math_score
math_score : [ 72  69  90  47  76  71  88  40  64  38  58  65  78  50  18  46  54  66
  44  74  73  67  70  62  63  56  97  81  75  57  55  53  59  82  77  33
  52   0  79  39  45  60  61  41  49  30  80  42  27  43  68  85  98  87
  51  99  84  91  83  89  22 100  96  94  48  35  34  86  92  37  28  24
  26  95  36  29  32  93  19  23   8]

Column : reading_score
reading_score : [ 72  90  95  57  78  83  43  64  60  54  52  81  53  75  89  32  42  58
  69  73  71  74  70  65  87  56  61  84  55  44  41  85  59  17  39  80
  37  63  51  49  26  68  45  47  86  34  79  66  67  91 100  76  77  82
  92  93  62  88  50  28  48  46  23  38  94  97  99  31  96  24  29  40]

Column : writing_score
writing_score : [ 74  88  93  44  75  78  92  39  67  50  52  43  73  70  58  86  28  46
  61  63  53  80  72  55  65  38  82  79  83  59  57  54  68  66  62  76
  48  42  87  49  10  34  71  37  56  41  22  81  45  36  89  47  90 100
  64  98  51  40  84  69  33  60  85  91  77  27  94  95  19  35  32  96
  97  99  15  30  23]

Column : total_score
total_score : [218 247 278 148 229 232 275 122 195 164 135 219 220 161 222 263  78 134
 173 198 210 151 215 225 178 211 205 207 217 189 193 120 266 241 238 253
 170 199 176 190 160 182 213 248 156 214 139 242 117 175  27 112 192 119
 206 194 181 140 174 123 239 146 115 235 216  97 221 138 257 187 265 274
 197 287 264 166 154 163 299 260 272 236 268 255 130 231 240 228 201 185
 147  94 224 293 212 150 180 234 296 155 246 200 259 158 184 297 204 196
 145 252 168 162 153 233 237 223 142  90 167 245 191 277 131 249 157 244
 227 282 149 270 186 226 129 267 230 136 183 202 250 203  70 171 271 143
  89 177 179  93 188 280 132 124 269 169 165 256 172 114 289 300 258 262
  95 209 243 273 276 261 208 104 292 279 291  69  88 251 152 144 159 113
 254 116 127 126 118 141 137 103 290 281 288  92 133  55]

Column : average_score
average_score : [ 72.67  82.33  92.67  49.33  76.33  77.33  91.67  40.67  65.    54.67
  45.    73.    73.33  53.67  74.    87.67  26.    44.67  57.67  66.
  70.    50.33  71.67  75.    59.33  70.33  68.33  69.    72.33  63.
  64.33  40.    88.67  80.33  79.33  84.33  56.67  66.33  58.67  63.33
  53.33  60.67  71.    82.67  52.    71.33  46.33  80.67  39.    58.33
   9.    37.33  64.    39.67  68.67  64.67  60.33  46.67  58.    41.
  79.67  48.67  38.33  78.33  72.    32.33  73.67  46.    85.67  62.33
  88.33  91.33  65.67  95.67  88.    55.33  51.33  54.33  99.67  86.67
  90.67  78.67  89.33  85.    43.33  77.    80.    76.    67.    61.67
  49.    31.33  74.67  97.67  70.67  50.    60.    78.    98.67  51.67
  82.    66.67  86.33  52.67  61.33  99.    68.    65.33  48.33  84.
  56.    54.    51.    77.67  79.    74.33  47.33  30.    55.67  81.67
  63.67  92.33  43.67  83.    52.33  81.33  75.67  94.    49.67  90.
  62.    75.33  43.    89.    76.67  45.33  61.    67.33  83.33  67.67
  23.33  57.    90.33  47.67  29.67  59.    59.67  31.    62.67  93.33
  44.    41.33  89.67  56.33  55.    85.33  57.33  38.    96.33 100.
  86.    87.33  31.67  69.67  81.    91.    92.    87.    69.33  34.67
  97.33  93.    97.    23.    29.33  83.67  50.67  48.    53.    37.67
  84.67  38.67  42.33  42.    39.33  47.    45.67  34.33  96.67  93.67
  96.    30.67  44.33  18.33]

In [6]:
num_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_features = df.select_dtypes(include=['object']).columns.tolist()

In [7]:
df['total_score'] = df['math_score'] + df['reading_score'] + df['writing_score']
df['average_score'] = (df['total_score'] / 3).round(2)

In [8]:
df.head(10)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.67
1,female,group C,some college,standard,completed,69,90,88,247,82.33
2,female,group B,master's degree,standard,none,90,95,93,278,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.33
4,male,group C,some college,standard,none,76,78,75,229,76.33
5,female,group B,associate's degree,standard,none,71,83,78,232,77.33
6,female,group B,some college,standard,completed,88,95,92,275,91.67
7,male,group B,some college,free/reduced,none,40,43,39,122,40.67
8,male,group D,high school,free/reduced,completed,64,64,67,195,65.00
9,female,group B,high school,free/reduced,none,38,60,50,148,49.33